services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: calories
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
volumes:
  postgres_data:
    driver: local

networks:
  my-network:
    driver: bridge